# -*- coding: utf-8 -*-
"""varanaras git.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L9xu0siIG0-IFGMOmeTcmoL4r2ANVCB9
"""

!git clone https://github.com/ashwiniambastha/Varanasi-GI-Toy-Cluster-Sustainability-Survey.git

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/Varanasi-GI-Toy-Cluster-Sustainability-Survey

# =============================================================================
# VARANASI TOY SURVEY - MAIN ENTRY POINT
# =============================================================================
"""
Main execution file for the Varanasi GI Toy Survey Analysis Project
This file orchestrates the entire data science pipeline
"""

import os
import sys
import warnings
warnings.filterwarnings('ignore')

# Import custom modules
from src.data_loader import load_and_explore_data
from src.eda_analysis import perform_advanced_eda
from src.feature_engineering import engineer_features
from src.preprocessing import preprocess_data
from src.ml_models import compare_ml_algorithms
from src.clustering_analysis import perform_clustering
from src.business_impact import analyze_business_impact
from src.visualizations import create_comprehensive_dashboard
from src.utils import setup_directories, save_results

def main():
    """
    Main execution function that runs the complete analysis pipeline
    """
    print("🎯 VARANASI TOY SURVEY - COMPREHENSIVE DATA SCIENCE ANALYSIS")
    print("=" * 70)

    # Setup project directories
    setup_directories()

    # Step 1: Load and explore data
    print("\n📊 STEP 1: DATA LOADING & EXPLORATION")
    df = load_and_explore_data('/content/Varanasi-GI-Toy-Cluster-Sustainability-Survey/data/varanasi_gi_toy_cluster_survey (1).csv')

    # Step 2: Advanced EDA
    print("\n📈 STEP 2: ADVANCED EXPLORATORY DATA ANALYSIS")
    eda_results = perform_advanced_eda(df)

    # Step 3: Feature Engineering
    print("\n🔧 STEP 3: FEATURE ENGINEERING")
    df_engineered, feature_list = engineer_features(df)

    # Step 4: Data Preprocessing
    print("\n🔄 STEP 4: DATA PREPROCESSING")
    df_processed, encoders, scaler = preprocess_data(df_engineered)

    # Step 5: ML Algorithms Comparison
    print("\n🤖 STEP 5: MACHINE LEARNING ALGORITHMS")
    ml_results = compare_ml_algorithms(df_engineered)

    # Step 6: Clustering Analysis
    print("\n🎯 STEP 6: CLUSTERING ANALYSIS")
    cluster_results = perform_clustering(df_engineered)

    # Step 7: Business Impact Analysis
    print("\n💼 STEP 7: BUSINESS IMPACT ANALYSIS")
    impact_results = analyze_business_impact(df_engineered)

    # Step 8: Create Comprehensive Dashboard
    print("\n📊 STEP 8: GENERATING VISUALIZATIONS")
    create_comprehensive_dashboard(df_engineered, ml_results, cluster_results, impact_results)

    # Step 9: Save Final Results
    print("\n💾 STEP 9: SAVING RESULTS")
    all_results = {
        'eda': eda_results,
        'ml': ml_results,
        'clustering': cluster_results,
        'business_impact': impact_results,
        'feature_count': len(feature_list)
    }
    save_results(df_engineered, all_results)

    print("\n✅ ANALYSIS COMPLETED SUCCESSFULLY!")
    print("📁 Check the 'results/' and 'visualizations/' directories for outputs")

if __name__ == "__main__":
    main()

